name: CI - Build and Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:

  backend-check:
    name: Backend Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: "22"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm ci

      - name: Check backend syntax
        working-directory: ./backend
        run: node --check server.js


  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Build backend image
        run: |
          docker build \
            -t k8s-task-manager-backend:test \
            ./backend

      - name: Build frontend image
        run: |
          docker build \
            -t k8s-task-manager-frontend:test \
            ./frontend
